
const desktopDisplay = [
  ['Desktop', undefined, undefined, undefined, undefined, undefined],
  [1.1,
    'Desktop -- display home page\n    /',
    'Page displays at desktop sizes without elements overflowing or breaking the page layout',
    'Mostly as expected',
    'Pass (95%)',
    'At very small display heights, text can be pushed underneath header.\nMinor issue - few use cases result in this behaviour.\nShould be fixed eventually.',
  ],
  [1.2,
    'Desktop -- display menu\n    /menu',
    'Same as 1.1',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [1.3,
    'Desktop -- display dish details\n    /menu/<dish_slug>',
    'Same as 1.1',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [1.4,
    'Desktop -- display contact page\n    /contact',
    'Same as 1.1',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [1.5,
    'Desktop -- display FAQs page\n    /faqs',
    'Same as 1.1',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [1.6,
    'Desktop -- display about page\n    /about-us',
    'Same as 1.1',
    'As expected',
    'Pass (100%)',
    '-',
  ],
];

const mobileDisplay = [
  ['Mobile', undefined, undefined, undefined, undefined, undefined],
  [2.1,
    'Mobile -- display home page\n    /',
    'Page displays at mobile resolutions without elements overflowing or breaking the page layout',
    'Somewhat as expected',
    'Pass (75%)',
    'Very short heights cause text and call to action to become hidden. Only likely to be a problem when browsing in landscape view.\nMedium issue - should be prioritised.',
  ],
  [2.2,
    'Mobile -- display menu\n    /menu',
    'Same as 2.1',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [2.3,
    'Mobile -- display dish details\n    /menu/<dish_slug>',
    'Same as 2.1',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [2.4,
    'Mobile -- display contact page\n    /contact',
    'Same as 2.1',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [2.5,
    'Mobile -- display FAQs page\n    /faqs',
    'Same as 2.1',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [2.6,
    'Mobile -- display about page\n    /about-us',
    'Same as 2.1',
    'As expected',
    'Pass (100%)',
    '-',
  ],
];

const adminDisplay = [
  ['Admin', undefined, undefined, undefined, undefined, undefined],
  [3.1,
    'Admin -- display login page\n    /login',
    'Page displays at desktop sizes without elements overflowing or breaking the page layout',
    'Somewhat as expected',
    'Pass (85%)',
    'Smaller widths and heights cause some overlapping elements.\nMinor issue - not breaking.',
  ],
  [3.2,
    'Admin -- display menu list\n    /staff/dishes',
    'Same as 3.1',
    'Mostly as expected',
    'Pass (99%)',
    'Viewport can be broken at small display heights, causing overflowing and hidden links.\nNon-issue - not recommended & unlikely to ever use the admin interface at such resolutions.',
  ],
  [3.3,
    'Admin -- display add dish form\n    /staff/dishes/add',
    'Same as 3.1',
    'Mostly as expected',
    'Pass (99%)',
    'Same as 3.2',
  ],
  [3.4,
    'Admin -- display edit dish form\n    /staff/dishes/<dish_id>',
    'Same as 3.1',
    'Mostly as expected',
    'Pass (99%)',
    'Same as 3.2',
  ],
  [3.5,
    'Admin -- display message list\n    /staff/messages',
    'Same as 3.1',
    'Mostly as expected',
    'Pass (99%)',
    'Same as 3.2',
  ],
  [3.6,
    'Admin -- display message details\n    /staff/messages/<msg_id>',
    'Same as 3.1',
    'Mostly as expected',
    'Pass (99%)',
    'Same as 3.2',
  ],
  [3.7,
    'Admin -- display FAQs list\n    /staff/faqs',
    'Same as 3.1',
    'Mostly as expected',
    'Pass (99%)',
    'Same as 3.2',
  ],
  [3.8,
    'Admin -- display add FAQ form\n    /staff/faqs/add',
    'Same as 3.1',
    'Mostly as expected',
    'Pass (99%)',
    'Same as 3.2',
  ],
  [3.9,
    'Admin -- display edit FAQ form\n    /staff/faqs/<faq_id>',
    'Same as 3.1',
    'Mostly as expected',
    'Pass (99%)',
    'Same as 3.2',
  ],
  ['3.10',
    'Admin -- display register form\n    /staff/register',
    'Same as 3.1',
    'Mostly as expected',
    'Pass (99%)',
    'Same as 3.2',
  ],
];

const functions = [
  ['Functions', undefined, undefined, undefined, undefined, undefined],
  [4.1,
    'Function -- mobile nav dropdown',
    'At the smallest break point, the hamburger menu should display the navigation links.',
    'Mostly as expected',
    'Pass (99%)',
    'At very small heights, the lower navigation links can be obstructed.\nNon-issue - unlikely that many displays possess a height this small.',
  ],
  [4.2,
    'Function -- navigation links\n(desktop & mobile)',
    'Each navigation link should correspond to its associated page.',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [4.3,
    'Function -- Home page call to action button',
    'This should navigate the the menu page.',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [4.4,
    'Function -- Footer staff login button',
    'This should navigate the the login page.',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [4.5,
    'Function -- Dish cards links in the menu list',
    'These should each navigate to their associated page, showing more details of the chosen dish.',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [4.6,
    'Function -- Showing all FAQs',
    'This link should navigate to the FAQs list.',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [4.7,
    'Function -- Submit contact form',
    'The contact form should be able to be filled in to send a message to the restaurant staff.',
    'Inadequate',
    'Pass (50%)',
    'Works, but there\'s no feedback to suggest that the message has been sent after the form has been submitted. From a UX perspective, this would be considered a serious problem.\nMajor issue - needs fixed.',
  ],
  [4.8,
    'Function -- Authentication',
    'A successful login should authorise the user to access the admin section.',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [4.9,
    'Function -- Logging out',
    'A logout should remove the privileges allowing access to the admin section.',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  ['4.10',
    'Function -- Protected admin interface',
    'Unauthorised users should be unable to access any URL starting with /staff and be redirected to the login page.',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [4.11,
    'Function -- Once authorised, redirect from login',
    'After logging in, any attempt to access the login page should redirect to the admin section.',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [4.12,
    'Function -- Sidebar navigation link',
    'Each link in the admin section\'s sidebar should navigate to its associated section/page.',
    'As expected',
    'Pass (100%)',
    '-',
  ],
  [4.13,
    'Function -- New admin registration',
    'The register form should create a new admin user once submitted.',
    'Mostly as expected',
    'Pass (90%)',
    'Similar to the contact form, no feedback is provided. However, an attempt can be made to log in after creating the account to check if it exists.',
  ],
  [4.14,
    'Function -- Dish removal',
    'Remove button should delete the dish from the database.',
    'As expected',
    'Pass (100%)',
    'Feedback is provided after redirecting to the dish list.',
  ],
  [4.15,
    'Function -- Adding a dish',
    'Submitting the add dish form should add the new dish to the database.',
    'As expected',
    'Pass (100%)',
    'Same as 4.14.',
  ],
  [4.16,
    'Function -- Updating a dish',
    'Submitting the edit dish form should update the dish\'s details in the database.',
    'Mostly as expected',
    'Pass (99%)',
    'Limited information is shown in the dish listings, so viewing the edit form can sometimes be necessary to check if certain details were updated.\nMinor inconvience.',
  ],
  [4.17,
    'Function -- FAQ removal',
    'Remove button should delete the FAQ from the database.',
    'As expected',
    'Pass (100%)',
    'Feedback is provided after redirecting to the FAQ list.',
  ],
  [4.18,
    'Function -- Adding a FAQ',
    'Submitting the add FAQ form should add the new FAQ to the database.',
    'As expected',
    'Pass (100%)',
    'Same as 4.17.',
  ],
  [4.19,
    'Function -- Updating a FAQ',
    'Submitting the edit FAQ form should update the FAQ\'s details in the database.',
    'As expected',
    'Pass (100%)',
    'Same as 4.17.',
  ],
  ['4.20',
    'Function -- Viewing an unread message',
    'Reading an unread message should mark it as read and change its appearance in the message list.',
    'As expected',
    'Pass (100%)',
    'Feedback is provided after redirecting to the message list.',
  ],
];

module.exports = [
  ...desktopDisplay,
  ...mobileDisplay,
  ...adminDisplay,
  ...functions,
];
